M48
; DRILL file {KiCad 8.0.0} date 2024-03-12T14:17:27+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-12T14:17:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X220.5Y-107.0
X222.5Y-90.0
T2
X212.229Y-118.709
M30
